//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneRepairApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_models
    {
        public int model_id { get; set; }
        public string brand { get; set; }
        public string model_name { get; set; }
        public Nullable<int> release_year { get; set; }
        public string storage_capacity { get; set; }
        public string color { get; set; }
    
        public virtual repair_orders repair_orders { get; set; }
        public virtual technicians technicians { get; set; }
    }
}
