//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneRepairApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class technicians
    {
        public int technician_id { get; set; }
        public string full_name { get; set; }
        public string specialization { get; set; }
        public Nullable<int> experience_years { get; set; }
        public Nullable<System.TimeSpan> available_from { get; set; }
        public Nullable<System.TimeSpan> available_to { get; set; }
    
        public virtual phone_models phone_models { get; set; }
    }
}
